#!/usr/bin/env bash

##
# greps through the ssh config file for the term passed in
# any 'or' statement needs to be in quotes
##
function parseSshConfig () {
  cat ./temp > ./grepTemp
  egrep -i "$1" ./grepTemp > ./temp
  rm -rf ./grepTemp
}

##
# Main control loop
##
touch ~/.ssh/config # makes sure config file exists
cat ~/.ssh/config > ./temp # outputs to temp file
while test $# -gt 0; do
  echo $1
  parseSshConfig $1
  shift
done  # loops though greping for each arg passed in

cat ./temp  # prints out final lines
rm -rf ./temp  # removes temp file
