#!/usr/bin/env node

const { git } = require('./js');
const program = require('commander');

program
  .option('s, start <name>', 'creates a new hotfix branch')
  .option('e, end <name>', 'ends a hotfix branch')
  .option('delete <name>', 'deletes a branch')
  .parse(process.argv);

if (program.hasOwnProperty('start')) {
  start();
}

function start () {
  git.checkout('master');
  git.pull();
  git.checkout(`hotfix/${program.start}`, '-b');
  git.publish(`hotfix/${program.start}`);
}
