#!/usr/bin/env node

const { git } = require('./js');
const program = require('commander');

program
  .option('s, start <name>', 'creates a new release branch')
  .option('e, end <name>', 'ends a release branch')
  .option('delete <name>', 'deletes a branch')
  .parse(process.argv);

if (startRelease()) {
  start();
} else if (finishRelease()) {
  finish();
} else if (program.hasOwnProperty('delete')) {
  removeBranch();
}

function removeBranch () {
  git.deleteBranch(`release/${program.delete}`);
}

function start () {
  git.checkout('develop');
  git.pull();
  git.checkout(`release/${program.start}`, '-b');
  git.publish(`release/${program.start}`);
}

function finish () {
  git.checkout(`release/${program.end}`);
  git.commit(`${program.end} release finish`);
  git.push();
  git.tag(`${program.end}`);
  git.createPullRequest(`release/${program.end}`, `develop`);
  git.createPullRequest(`release/${program.end}`, `master`);
}

function finishRelease () {
  return program.hasOwnProperty('end')
      || program.hasOwnProperty('finish')
      || program.hasOwnProperty('close');
}

function startRelease () {
  return program.hasOwnProperty('start')
      || program.hasOwnProperty('begin');
}
