#!/usr/bin/env node

const { git, cloud } = require('./js');
const program = require('commander');

program
  .arguments('<cmd> <branch>')
  .action(action)
  .parse(process.argv);

branch = `hotfix/${branch}`;
if (startHotfix()) {
  start();
} else if (finishHotfix()) {
  finish();
} else if (program.hasOwnProperty('delete')) {
  removeBranch();
}

function action ( cmd, brch ){
  command = cmd;
  branch = brch;
}

function removeBranch () {
  git.deleteBranch(branch);
}

function start () {
  git.checkout('master');
  git.pull();
  git.checkout(branch);
  git.publish(branch);
}

function finish () {
  git.checkout(branch);
  git.commit(`${branch} hotfix finish`);
  git.push();
  git.tag(branch);
  git.createPullRequest(branch, `master`);
}

function finishHotfix () {
  return command == 'end'
      || command == 'finish'
      || command == 'close';
}

function startHotfix () {
  return command == 'begin'
      || command == 'start';
}
