#!/usr/bin/env bash

branch=$1
echo $branch
if [[ ! -z "$branch" ]]; then
  if [[ -z "$(git branch --all | grep '$branch')" ]]; then
    echo "branch doesn't exist. creating"
    git pull
    git checkout -b $branch 
    git push --set-upstream origin $branch
  else
    git checkout $branch
    git pull
  fi
else
  echo 'No Arg supplied'
fi
