#!/usr/bin/env bash

branch=$1
if [[ ! -z "$branch" ]]; then
  git fetch
  if [[ $(git branch --all | grep "$branch") ]]; then
    git checkout $branch
    git pull
  else
    echo "branch doesn't exist. creating"
    git pull
    git checkout -b $branch 
    git push --set-upstream origin $branch
  fi
else
  echo 'No Arg supplied'
fi
