#!/usr/bin/env bash

help=(""
"Quick helper for the CLI Tools"
"Only current option:"
""
"list             prints list of current tools"
"")

list=(""
"RZ CLI Tools"
"Let's do some shit!"
""
"Current CLI Tools:"
"bit              pull request version of git flow"
"checkout         checkouts an existing branch or creates a new one"
"commit           skip the git and commit!"
"dev              connects to the dev database using the psqlFunction tool"
"feature          shortcut to creating a feature branch"
"hotfix           shortcut to creating a hotfix branch"
"ip               searches the stored host names and outputs matches"
"ipseed           gets current ec2 instance ips and stores them under host names"
"prod             connects to the prod database using the psqlFunction tool"
"pull             pulls the current branch or switches branches and pulls"
"push             pushes all commits or commits current changes then pushes"
"release          shortcut to creating a release branch"
"session          sets a temporary aws session for access aws cli commands"
"stage            connects to the stage database using the psqlFunction tool"
"")


###########################################################################
##                      MAIN CONTROL LOOP                                ##
###########################################################################
if [[ -z "$1" ]]; then
  # they didn't pass anything in. print out help menu
  printf "%s\n" "${help[@]}"
  exit 1
fi
case "$1" in
  # print out the help menu
  help)
    printf "%s\n" "${help[@]}"
    ;;
  # print out a list of current rz dev tools
  list)
    printf "%s\n" "${list[@]}"
    ;;
  # TODO: maybe something else too?
  # and default to help command
  *)
    echo "Not a recognized option"
    printf "%s\n" "${help[@]}"
esac

