#!/usr/bin/env bash



###########################################################################
##                      MAIN CONTROL LOOP                                ##
###########################################################################
# if there's only one arg, just use as commit message
if [ $# -eq 1 ]; then
  git commit -m "$1"
  exit 0
fi

EXTRAS=""
END="-m"
# check other args
while test $# -gt 1; do
  case $1 in
    --amend)
      END="--amend --no-edit "
      shift
      ;;
    -a)
      EXTRAS="-a $EXTRAS"
      shift
      ;;
  esac
done
git commit $EXTRAS $END $1
