#!/usr/bin/env bash

if [ -f package.json ]; then
  npm run test:coverage
fi
if [ -f *.sln ]; then
  dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude="[xunit*]\*" /p:CoverletOutput="./TestResults/"
  reportgenerator "-reports:src/*/TestResults/coverage.cobertura.xml" "-targetdir:TestResults/html" -reporttypes:HTML;
fi
