#!/usr/bin/env bash

grepOptions='-i'
ssh=false

function parseOptions () {
  while test $# -gt 0; do
    if [[ $1 == -* ]]; then
      echo "$1"
      case "$1" in 
        -i|--ip)
          grepOptions="$grepOptions -A 1"
          ;;
        *)
          ;;
      esac
      shift
    else
      break
    fi
  done
  echo "$grepOptions"
}

##
# greps through the ssh config file for the term passed in
# any 'or' statement needs to be in quotes
##
function parseSshConfig () {
  cat /tmp/temp > /tmp/grepTemp
  egrep $grepOptions "$1" /tmp/grepTemp > /tmp/temp
  rm -rf /tmp/grepTemp
}

##
# Main control loop
##
## TODO: add in ssh flag. mainly the logic
while test $# -gt 0; do
  if [[ $1 == -* ]]; then
    case "$1" in 
      -i|--ip)
        grepOptions="$grepOptions -A 1"
        ;;
      -s|--ssh)
        ssh=true
        ;;
      *)
        ;;
    esac
    shift
  else
    break
  fi
done
touch ~/.ssh/config # makes sure config file exists
cat ~/.ssh/config > /tmp/temp # outputs to temp file
while test $# -gt 0; do
  parseSshConfig $1
  shift
done  # loops though greping for each arg passed in

cat /tmp/temp  # prints out final lines
rm -rf /tmp/temp  # removes temp file
